openapiOptions:
  file:
    # the file name must be the same as one passed to protoc when generating generating .swagger.json
    - file: "hello.proto"
      option:
        info:
          title: poc-grpc-gateway
          contact:
            name: poc-grpc-gateway project
            email: max.focker.shih@gmail.com
          version: '1.0'
        host: "hello.poc-gateway.com"
        schemes:
          # - HTTP
          - HTTPS
          # - WSS
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          '403':
            description: Returned when the user does not have permission to access the resource.
          '404':
            description: Returned when the resource does not exist.
            schema:
              jsonSchema:
                type:
                  - STRING
          '418':
            description: I'm a teapot.
